apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx1
  name: nginx1
spec:
  ports:
  - port: 81
    protocol: TCP
    targetPort: 81
  selector:
    app: nginx1
  type: LoadBalancer
status:
  loadBalancer: {}
