apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nginx1
  name: nginx1
spec:
  ports:
  - port: 81
    nodePort: 31000
    targetPort: 81
  selector:
    app: nginx1
  type: NodePort
status:
  loadBalancer: {}
